### ISSUE TITLE
Aptitude and codecoverage build

### ISSUE THREAD

**Issue by ndepalma** [petroglyf/functional-dag#4]
Make sure codecoverage is working and also see if you can build a dpkg.

**Comment by ndepalma** [comment]
Also chocolatey

**Comment by Oyuki-kintaro** [comment]
I have installed chocolatey and will be working on building packages and creating an ubuntu image.

**Comment by Oyuki-kintaro** [comment]
Created and ran an ubuntu container from image. Used Powershell to start the container and was able to validate the container was running with Docker Desktop

![image](https://github.com/petrogly-ph/functional-dag/assets/69707473/45653b5e-6531-4877-8a8b-818275a99b3f)
